# Simulating Coin Flips

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
# outcome of one coin flip
np.random.randint(2)

1

In [19]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 1, 0, ..., 0, 0, 0])

In [21]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5081

In [22]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [24]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 1, 1, ..., 1, 1, 1])

In [27]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4926

In [29]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([1, 0, 0, ..., 0, 0, 0])

In [33]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.2078